-- 1. Create tables
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    employee_code TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'Employee',
    department TEXT,
    team_leader TEXT,
    is_blocked BOOLEAN DEFAULT false,
    contact_no TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code TEXT NOT NULL,
    date DATE NOT NULL,
    department TEXT NOT NULL,
    report1 TEXT,
    report2 TEXT,
    report3 TEXT,
    working_details TEXT,
    emp_name TEXT,
    contact_no TEXT,
    subtitle TEXT,
    hours_calculate TEXT,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    team_leader TEXT NOT NULL,
    team_leader_code TEXT,
    project_number TEXT NOT NULL,
    status TEXT DEFAULT 'Pending',
    tl_comments TEXT,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_number TEXT UNIQUE NOT NULL,
    description TEXT
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Optimize fetching an employee's history (filtered by employee_code, ordered by submitted_at)
CREATE INDEX IF NOT EXISTS idx_reports_employee_code ON reports(employee_code);
CREATE INDEX IF NOT EXISTS idx_reports_submitted_at ON reports(submitted_at DESC);

-- Optimize fetching pending reports for a Team Leader (filtered by team_leader and status)
CREATE INDEX IF NOT EXISTS idx_reports_team_leader_status ON reports(team_leader, status);

-- Optimize fetching notifications (filtered by user_id, ordered by created_at)
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at DESC);

-- Optimize checking for unread notifications (filtered by user_id and is_read)
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(user_id, is_read);

-- Optimize user lookups for drop-downs / filtering
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_team_leader ON users(team_leader);

-- 1. Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- USERS TABLE POLICIES
-- ============================================================

-- All authenticated users can read users (needed for dropdowns, TL lookups)
CREATE POLICY "users_select_authenticated"
  ON users FOR SELECT
  TO authenticated
  USING (true);

-- Only Admins can insert new users
CREATE POLICY "users_insert_admin"
  ON users FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM users u
      WHERE u.id = (auth.jwt() ->> 'sub')::bigint
      AND u.role = 'Admin'
    )
  );

-- Employees can update their own row; Admins/TLs can update any
CREATE POLICY "users_update_self_or_admin"
  ON users FOR UPDATE
  TO authenticated
  USING (
    employee_code = (
      SELECT u.employee_code FROM users u
      WHERE u.email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM users u
      WHERE u.email = auth.jwt() ->> 'email'
      AND u.role IN ('Admin', 'Team Leader')
    )
  );

-- Only Admins can delete users
CREATE POLICY "users_delete_admin"
  ON users FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users u
      WHERE u.email = auth.jwt() ->> 'email'
      AND u.role = 'Admin'
    )
  );

-- ============================================================
-- REPORTS TABLE POLICIES
-- ============================================================

-- Employees see own reports; TLs see reports assigned to them; Admins see all
CREATE POLICY "reports_select"
  ON reports FOR SELECT
  TO authenticated
  USING (
    employee_code = (
      SELECT u.employee_code FROM users u WHERE u.email = auth.jwt() ->> 'email'
    )
    OR team_leader_code = (
      SELECT u.employee_code FROM users u WHERE u.email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM users u
      WHERE u.email = auth.jwt() ->> 'email'
      AND u.role = 'Admin'
    )
  );

-- Employees can insert their own reports
CREATE POLICY "reports_insert_own"
  ON reports FOR INSERT
  TO authenticated
  WITH CHECK (
    employee_code = (
      SELECT u.employee_code FROM users u WHERE u.email = auth.jwt() ->> 'email'
    )
  );

-- TLs can update reports assigned to them (for review); Admins can update any
CREATE POLICY "reports_update_tl_or_admin"
  ON reports FOR UPDATE
  TO authenticated
  USING (
    team_leader_code = (
      SELECT u.employee_code FROM users u WHERE u.email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM users u
      WHERE u.email = auth.jwt() ->> 'email'
      AND u.role = 'Admin'
    )
  );

-- ============================================================
-- NOTIFICATIONS TABLE POLICIES
-- ============================================================

-- Users can only read their own notifications
CREATE POLICY "notifications_select_own"
  ON notifications FOR SELECT
  TO authenticated
  USING (
    user_id = (
      SELECT u.employee_code FROM users u WHERE u.email = auth.jwt() ->> 'email'
    )
  );

-- Users can update their own notifications (mark as read)
CREATE POLICY "notifications_update_own"
  ON notifications FOR UPDATE
  TO authenticated
  USING (
    user_id = (
      SELECT u.employee_code FROM users u WHERE u.email = auth.jwt() ->> 'email'
    )
  );

-- Notifications are inserted by triggers (SECURITY DEFINER), so we need
-- to allow the trigger function to bypass RLS. Update trigger functions:
CREATE OR REPLACE FUNCTION notify_tl_on_submission()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO notifications (user_id, message, type)
    VALUES (NEW.team_leader_code, 'New report submitted by ' || COALESCE(NEW.emp_name, NEW.employee_code), 'submission');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION notify_employee_on_review()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF OLD.status <> NEW.status THEN
        INSERT INTO notifications (user_id, message, type)
        VALUES (NEW.employee_code, 'Your report for ' || NEW.date || ' has been ' || NEW.status, 'status_update');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_notify_tl
    AFTER INSERT ON reports
    FOR EACH ROW
    EXECUTE FUNCTION notify_tl_on_submission();

CREATE TRIGGER trigger_notify_employee
    AFTER UPDATE ON reports
    FOR EACH ROW
    EXECUTE FUNCTION notify_employee_on_review();

-- ============================================================
-- PROJECTS TABLE POLICIES
-- ============================================================

-- All authenticated users can read projects
CREATE POLICY "projects_select_authenticated"
  ON projects FOR SELECT
  TO authenticated
  USING (true);

-- Only Admins can manage projects
CREATE POLICY "projects_insert_admin"
  ON projects FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM users u
      WHERE u.email = auth.jwt() ->> 'email'
      AND u.role = 'Admin'
    )
  );

CREATE POLICY "projects_update_admin"
  ON projects FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users u
      WHERE u.email = auth.jwt() ->> 'email'
      AND u.role = 'Admin'
    )
  );

CREATE POLICY "projects_delete_admin"
  ON projects FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users u
      WHERE u.email = auth.jwt() ->> 'email'
      AND u.role = 'Admin'
    )
  );
