-- SQL Schema for Supabase "faithhours" project

-- Create Users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    employee_code TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'Employee',
    department TEXT,
    team_leader TEXT,
    is_blocked BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Reports table
CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code TEXT NOT NULL,
    date DATE NOT NULL,
    department TEXT NOT NULL,
    report1 TEXT,
    report2 TEXT,
    report3 TEXT,
    working_details TEXT,
    emp_name TEXT,
    contact_no TEXT,
    subtitle TEXT,
    hours_calculate TEXT,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    team_leader TEXT NOT NULL,
    team_leader_code TEXT,
    project_number TEXT NOT NULL,
    status TEXT DEFAULT 'Pending',
    tl_comments TEXT,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ
);

-- Create Projects table
CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_number TEXT UNIQUE NOT NULL,
    description TEXT
);

-- Create Notifications table
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- This will store employee_code
    message TEXT NOT NULL,
    type TEXT NOT NULL, -- 'reminder', 'alert', 'status_update'
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Realtime for notifications
ALTER PUBLICATION supabase_realtime ADD TABLE notifications;

-- Function to notify TL on new report
CREATE OR REPLACE FUNCTION notify_tl_on_submission()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO notifications (user_id, message, type)
    VALUES (NEW.team_leader_code, 'New report submitted by ' || COALESCE(NEW.emp_name, NEW.employee_code), 'submission');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_notify_tl
AFTER INSERT ON reports
FOR EACH ROW EXECUTE FUNCTION notify_tl_on_submission();

-- Function to notify employee on review
CREATE OR REPLACE FUNCTION notify_employee_on_review()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status <> NEW.status THEN
        INSERT INTO notifications (user_id, message, type)
        VALUES (NEW.employee_code, 'Your report for ' || NEW.date || ' has been ' || NEW.status, 'status_update');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_notify_employee
AFTER UPDATE ON reports
FOR EACH ROW EXECUTE FUNCTION notify_employee_on_review();

-- Enable Row Level Security (RLS) or disable for now if you want open access
-- ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- Database Indices for Query Optimization
CREATE INDEX IF NOT EXISTS idx_reports_employee_code ON reports(employee_code);
CREATE INDEX IF NOT EXISTS idx_reports_submitted_at ON reports(submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_reports_team_leader_status ON reports(team_leader, status);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_team_leader ON users(team_leader);
