-- SQL Schema for Supabase "officegate" project

-- Create Users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    employee_code TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'Employee',
    department TEXT,
    team_leader TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Reports table
CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code TEXT NOT NULL,
    date DATE NOT NULL,
    department TEXT NOT NULL,
    report1 TEXT NOT NULL,
    report2 TEXT,
    report3 TEXT,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    team_leader TEXT NOT NULL,
    project_number TEXT NOT NULL,
    status TEXT DEFAULT 'Pending',
    tl_comments TEXT,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ
);

-- Create Notifications table
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- This will store employee_code
    message TEXT NOT NULL,
    type TEXT NOT NULL, -- 'reminder', 'alert', 'status_update'
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Realtime for notifications
ALTER PUBLICATION supabase_realtime ADD TABLE notifications;

-- Function to notify TL on new report
CREATE OR REPLACE FUNCTION notify_tl_on_submission()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO notifications (user_id, message, type)
    VALUES (NEW.team_leader, 'New report submitted by ' || NEW.employee_code, 'submission');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_notify_tl
AFTER INSERT ON reports
FOR EACH ROW EXECUTE FUNCTION notify_tl_on_submission();

-- Function to notify employee on review
CREATE OR REPLACE FUNCTION notify_employee_on_review()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status <> NEW.status THEN
        INSERT INTO notifications (user_id, message, type)
        VALUES (NEW.employee_code, 'Your report for ' || NEW.date || ' has been ' || NEW.status, 'status_update');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_notify_employee
AFTER UPDATE ON reports
FOR EACH ROW EXECUTE FUNCTION notify_employee_on_review();

-- Enable Row Level Security (RLS) or disable for now if you want open access
-- ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
